name: issue comment workflow

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo 'github context: ${{ toJSON(github.event) }}'
        shell: bash
